base_url = "https://wawona.github.io"
title = "Wawona"
description = "A native Wayland substrate for macOS, iOS, and Android"
theme = "apollo"
default_language = "en"
compile_sass = true
minify_html = true
build_search_index = true
taxonomies = [{ name = "tags" }]

[search]
index_format = "elasticlunr_javascript"
include_title = true
include_description = true
include_path = true
include_content = true


[markdown]
highlighting = { theme = "solarized-dark" }
external_links_target_blank = true

[extra]
index_format = "elasticlunr_javascript"

author = "Wawona Team"
theme = "toggle" # dark, light, auto, toggle
favicon = "images/logo/wawona.png"
logo = "images/logo/wawona.png"
fancy_code = true

menu = [
    { name = "/posts", url = "posts", weight = 1 },
    { name = "/docs", url = "docs", weight = 2 },
    { name = "/faq", url = "faq", weight = 3 },
    { name = "/gallery", url = "gallery", weight = 4 },
    { name = "/download", url = "download", weight = 5 },
]

socials = [
    { name = "github", url = "https://github.com/aspauldingcode/Wawona", icon = "github" },
]
